inherit_from: .rubocop_todo.yml

inherit_gem:
  theforeman-rubocop:
    - rules/base.yml
    - rules/ruby_target.yml
    - rules/style.yml
    - rules/performance.yml

AllCops:
  TargetRubyVersion: '2.7'
  Exclude:
    - 'test/**/*'
    - 'vendor/**/*'

Metrics:
  Enabled: false

Layout:
  Enabled: true

Style:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: true
